### ISSUE TITLE
Simple bash script

### ISSUE THREAD

**Issue by sy6sy2** [SteveHan-233/MTS-mp4-converter-Apple-Photos#1]
Hey! Thanks for the commands.

If anyone want to convert all MTS files from a directory without Go, just do the following:

1. Open a Terminal and move in folder that contains all your MTS movies.
2. Run this command to convert all MTS movies in MP4 file: `for f in *; do ffmpeg -i $f -c:v libx265 -preset fast -crf 28 -tag:v hvc1 -c:a eac3 -b:a 224k $f.mp4 && exiftool -tagsFromFile $f -time:all $f.mp4; done`

**Comment by han-steve** [comment]
Thanks for the bash script! Yeah the Go is unnecessary for most cases. I'll add it to the readme!
